hip_kx : 2
hip_ky : 2
an_kx  : 30
an_ky  : -30




r_leg_hip_y_ofst : 0
r_leg_hip_r_ofst : 0
r_leg_hip_p_ofst : 0
r_leg_kn_p_ofst  : 0
r_leg_an_p_ofst  : 0
r_leg_an_r_ofst  : 0

l_leg_hip_y_ofst : 0
l_leg_hip_r_ofst : 0
l_leg_hip_p_ofst : 180
l_leg_kn_p_ofst  : 149
l_leg_an_p_ofst  : 205
l_leg_an_r_ofst  : 162









