thormang3:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 125  
  
  # Position Controllers ---------------------------------------
  
  # Body ------


  # Left Leg -----

  l_leg_hip_y_position:
    type: effort_controllers/JointPositionController
    joint: l_leg_hip_y
    pid: {p: 100.0, i: 0.01, d: 10.0}

  l_leg_hip_r_position:
    type: effort_controllers/JointPositionController
    joint: l_leg_hip_r
    pid: {p: 100.0, i: 0.01, d: 10.0}

  l_leg_hip_p_position:
    type: effort_controllers/JointPositionController
    joint: l_leg_hip_p
    pid: {p: 100.0, i: 0.01, d: 10.0}

  l_leg_kn_p_position:
    type: effort_controllers/JointPositionController
    joint: l_leg_kn_p
    pid: {p: 100.0, i: 0.01, d: 10.0}

  l_leg_an_p_position:
    type: effort_controllers/JointPositionController
    joint: l_leg_an_p
    pid: {p: 100.0, i: 0.01, d: 10.0}

  l_leg_an_r_position:
    type: effort_controllers/JointPositionController
    joint: l_leg_an_r
    pid: {p: 100.0, i: 0.01, d: 10.0}

  # Right Leg -----

  r_leg_hip_y_position:
    type: effort_controllers/JointPositionController
    joint: r_leg_hip_y
    pid: {p: 100.0, i: 0.01, d: 10.0}

  r_leg_hip_r_position:
    type: effort_controllers/JointPositionController
    joint: r_leg_hip_r
    pid: {p: 100.0, i: 0.01, d: 10.0}

  r_leg_hip_p_position:
    type: effort_controllers/JointPositionController
    joint: r_leg_hip_p
    pid: {p: 100.0, i: 0.01, d: 10.0}

  r_leg_kn_p_position:
    type: effort_controllers/JointPositionController
    joint: r_leg_kn_p
    pid: {p: 100.0, i: 0.01, d: 10.0}

  r_leg_an_p_position:
    type: effort_controllers/JointPositionController
    joint: r_leg_an_p
    pid: {p: 100.0, i: 0.01, d: 10.0}

  r_leg_an_r_position:
    type: effort_controllers/JointPositionController
    joint: r_leg_an_r
    pid: {p: 100.0, i: 0.01, d: 10.0}

 
